services:
  workspace:
    build: .
    container_name: ds_workspace
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    volumes:
      - ./notebooks:/app/notebooks
